/** Frases para cada acción auditada ("Ana Gómez ___"). Las que falten se muestran con su código. */
export const ACTION_LABEL: Record<string, string> = {
  'attendance.adjusted': 'ajustó una marcación',
  'attendance.reviewed': 'revisó una marcación',
  'company.created': 'creó la empresa',
  'company.updated': 'editó los datos de la empresa',
  'company.settings_updated': 'cambió la configuración de la empresa',
  'company.status_changed': 'cambió el estado de la empresa',
  'company.invitation_resent': 'reenvió la invitación del administrador',
  'contract.created': 'registró un contrato',
  'contract.updated': 'editó un contrato',
  'employee.created': 'creó un empleado',
  'employee.updated': 'editó un empleado',
  'employee.status_changed': 'cambió el estado de un empleado',
  'employee.access_granted': 'dio acceso a la app a un empleado',
  'employee.imported': 'importó empleados desde Excel',
  'geofence.created': 'creó una geocerca',
  'geofence.updated': 'editó una geocerca',
  'geofence.deleted': 'eliminó una geocerca',
  'incident.requested': 'reportó una novedad',
  'incident.approved': 'aprobó una novedad',
  'incident.rejected': 'rechazó una novedad',
  'incident.cancelled': 'canceló una novedad',
  'incident.revoked': 'revocó una novedad aprobada',
  'position.created': 'creó un cargo',
  'position.updated': 'editó un cargo',
  'role.created': 'creó un rol',
  'role.updated': 'editó un rol',
  'role.deleted': 'eliminó un rol',
  'schedule_period.created': 'creó un periodo de programación',
  'schedule_period.updated': 'editó un periodo de programación',
  'schedule_period.deleted': 'eliminó un periodo en borrador',
  'schedule_period.published': 'publicó un periodo',
  'schedule_period.closed': 'cerró un periodo',
  'shift.created': 'creó un turno',
  'shift.bulk_created': 'creó turnos en lote',
  'shift.updated': 'cambió el horario de un turno',
  'shift.cancelled': 'canceló un turno',
  'shift.employees_assigned': 'asignó personas a un turno',
  'shift.employee_unassigned': 'retiró a una persona de un turno',
  'shift_change.requested': 'solicitó un cambio de turno',
  'shift_change.peer_accepted': 'aceptó un cambio de turno',
  'shift_change.peer_declined': 'rechazó un cambio de turno propuesto',
  'shift_change.approved': 'aprobó un cambio de turno',
  'shift_change.rejected': 'rechazó un cambio de turno',
  'shift_change.cancelled': 'canceló una solicitud de cambio de turno',
  'store.created': 'creó un establecimiento',
  'store.updated': 'editó un establecimiento',
  'user.created': 'creó un usuario',
  'user.invited': 'invitó a un usuario',
  'user.invitation_resent': 'reenvió una invitación',
  'user.membership_added': 'dio acceso a la empresa a una cuenta existente',
  'user.role_changed': 'cambió el rol de un usuario',
  'user.status_changed': 'cambió el acceso de un usuario',
  'user.password_reset_requested': 'envió un enlace para cambiar la contraseña',
  'user.password_changed': 'cambió su contraseña',
  'user.password_reset': 'restableció su contraseña con un enlace',
  'notification.announcement_sent': 'envió un aviso',
};

/** Filtros por prefijo de acción (el backend filtra por "empieza por"). */
export const CATEGORIES: [string, string][] = [
  ['attendance.', 'Asistencia'],
  ['shift.', 'Turnos'],
  ['schedule_period.', 'Periodos'],
  ['shift_change.', 'Cambios de turno'],
  ['incident.', 'Novedades'],
  ['employee.', 'Empleados'],
  ['contract.', 'Contratos'],
  ['store.', 'Establecimientos'],
  ['geofence.', 'Geocercas'],
  ['user.', 'Usuarios'],
  ['role.', 'Roles'],
  ['company.', 'Empresa'],
  ['notification.', 'Avisos'],
];

/** Nombres legibles para los campos que aparecen en "antes / después". */
export const FIELD_LABEL: Record<string, string> = {
  name: 'Nombre',
  legalName: 'Razón social',
  taxId: 'NIT',
  timezone: 'Zona horaria',
  status: 'Estado',
  reason: 'Motivo',
  firstName: 'Nombres',
  lastName: 'Apellidos',
  email: 'Correo',
  phone: 'Teléfono',
  role: 'Rol',
  roleId: 'Rol',
  permissions: 'Permisos',
  description: 'Descripción',
  startsAt: 'Inicio',
  endsAt: 'Fin',
  startDate: 'Desde',
  endDate: 'Hasta',
  breakMinutes: 'Descanso (min)',
  earlyClockInMinutes: 'Marcar antes (min)',
  lateToleranceMinutes: 'Tolerancia (min)',
  radiusMeters: 'Radio (m)',
  maxAccuracyMeters: 'Precisión máxima (m)',
  centerLatitude: 'Latitud',
  centerLongitude: 'Longitud',
  latitude: 'Latitud',
  longitude: 'Longitud',
  isActive: 'Activo',
  notes: 'Notas',
  clockInAt: 'Entrada',
  clockOutAt: 'Salida',
  salary: 'Salario',
  employeeIds: 'Empleados',
  notifiedUsers: 'Personas notificadas',
  shiftDefaults: 'Reglas de turnos',
  address: 'Dirección',
  city: 'Ciudad',
  code: 'Código',
};

/** Campos técnicos que no aportan en el detalle. */
export const HIDDEN_FIELDS = new Set(['id', 'companyId', 'createdAt', 'updatedAt', 'passwordHash']);

export const ENTITY_LINK: Record<string, (id: string) => string> = {
  Employee: (id) => `/empleados/${id}`,
  Store: (id) => `/establecimientos/${id}`,
};
